{
 "title": "Kubernetes Bird's View Dashboard",
 "description": "A dashboard showing statuses of Pods and PVC's within the cluster and additional resource information, created by codesenju. https://github.com/codesenju/k8s-grafana-dashboards",
 "tags": [
  "prometheus",
  "kubernetes",
  "pvc",
  "pod"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Throttled seconds by namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\"}[5m])) by (namespace) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests & Limits by namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests{ unit=\"byte\"}) by (namespace)",
     "legendFormat": "{{ namespace }} REQUESTS"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits{unit=\"byte\"}) by (namespace)",
     "legendFormat": "{{ namespace }} LIMITS"
    }
   ]
  },
  {
   "title": "Pod Restarts by namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[5m])) by(namespace) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Terminated Reason by namespace",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\"}) by (reason,namespace) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Status | All Namespaces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace with pod in non-running status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!~\"Running\"}) by (phase,namespace)  > 0",
     "legendFormat": "{{phase}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace with pvc in non-bound status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}) by (phase,namespace)  > 0",
     "legendFormat": "{{phase}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Pod Status | All Namespaces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod/PVC status in $namespace namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\"}) by (phase,pod,namespace)  > 0",
       "legendFormat": "{{phase}} {{pod}}"
      }
     ]
    },
    {
     "title": "PVC's",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\"}) by (phase,persistentvolumeclaim,namespace)  > 0",
       "legendFormat": "{{phase}} {{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources in $namespace namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "CPU usage by Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[5m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage / Requests & Limits by container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", unit=\"byte\"}) by (container)",
       "legendFormat": "{{ container }} REQUESTS"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", unit=\"byte\"}) by (container)",
       "legendFormat": "{{ container }} LIMITS"
      }
     ]
    },
    {
     "title": "CPU Usage / Requests & Limits by container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image!=\"\"}[5m])) by (container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", unit=\"core\"}) by (container)",
       "legendFormat": "{{ container }}  REQUESTS"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",image!=\"\"}[5m])) by (container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", unit=\"core\"}) by (container)",
       "legendFormat": "{{ container }}  LIMITS"
      }
     ]
    },
    {
     "title": "CPU Throttled seconds by pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\",namespace=\"$namespace\"}[5m])) by (pod) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}