{
 "title": "K8s Pod/PVC Status",
 "description": "A dashboard showing statuses of Pods and PVC's within the cluster, created by codesenju. https://github.com/codesenju/k8s-grafana-dashboards",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Status | All Namespaces",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Status | All Namespaces",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace with pod in non-running status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!=\"Running\"}) by (phase,namespace)  > 0",
     "legendFormat": "{{phase}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace with pvc in non-bound status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}) by (phase,namespace)  > 0",
     "legendFormat": "{{phase}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Pod/PVC status in $namespace namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Pods",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\"}) by (phase,pod,namespace)  > 0",
     "legendFormat": "{{phase}} {{pod}}"
    }
   ]
  },
  {
   "title": "PVC's",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=~\"$namespace\"}) by (phase,persistentvolumeclaim,namespace)  > 0",
     "legendFormat": "{{phase}} {{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}