{
 "title": "k8s pod monitoring on litmus experiments v2",
 "description": "Litmus chaos on skillsets-api",
 "tags": [
  "litmus",
  "chaos engineering"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas_ready{namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "replicacount",
    "label": "replica_count",
    "query": {
     "query": "query_result(sum(kube_deployment_spec_replicas{deployment=\"$deployment\",namespace=\"$namespace\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Throttled seconds by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\", image!=\"\", pod=~\"${deployment}.*\"}[5m])) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources by container per pod",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$deployment.*\", unit=\"core\"}) by (container) / $replicacount"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$deployment.*\", unit=\"core\"}) by (container)/ $replicacount"
    }
   ]
  },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", pod=~\"${deployment}.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests & Limits by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\", unit=\"byte\",pod=~\"^$deployment.*\"}) by (container)\n",
     "legendFormat": "{{ container }} REQUESTS"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", image!=\"\"}) by (container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\", unit=\"byte\",pod=~\"^$deployment.*\"}) by (container)",
     "legendFormat": "{{ container }} LIMITS"
    }
   ]
  },
  {
   "title": "Resources by container per pod",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$deployment.*\", unit=\"byte\"}) by (container)/ $replicacount"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$deployment.*\", unit=\"byte\"}) by (container)/ $replicacount"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\",pod=~\"^$deployment.*\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_m_working_set_bytes{namespace=~\"$namespace\", image!=\"\",pod=~\"^$deployment.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"^$deployment.*\"}) by (phase,pod,namespace)  > 0",
     "legendFormat": "{{phase}} {{pod}}"
    }
   ]
  },
  {
   "title": "Resources by container per pod",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$deployment.*\", unit=\"core\"}) by (container) / $replicacount"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$deployment.*\", unit=\"core\"}) by (container)/ $replicacount"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$deployment.*\", unit=\"byte\"}) by (container)/ $replicacount"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$deployment.*\", unit=\"byte\"}) by (container)/ $replicacount"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$deployment.*\", image!=\"\", container!=\"\"}[5m])) by (container)/ $replicacount",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$deployment.*\", image!=\"\", container!=\"\"}) by (container)/ $replicacount"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{}[5m])) by(pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\",pod=~\"^$deployment.*\"}) by (reason,pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"$deployment\",namespace=\"$namespace\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}