{
 "title": "K8s Centralized Logging (Loki, fluentbit, Cloudwatch)",
 "description": "Container/Pod Log Dashboard(Loki as DataSource)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource_loki", "query": "loki" },
   { "name": "datasource_cw", "query": "cloudwatch" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({namespace=~\".+\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values({namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values({namespace=\"$namespace\"}, stream)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error" },
   { "name": "fargate_logging_search", "label": "fargate_logging_search", "query": "karpenter" }
  ]
 },
 "panels": [
  { "title": "EC2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({namespace=\"$namespace\", stream=~\"$stream\", pod=~\"$pod\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", pod=~\"$pod\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\""
    }
   ]
  },
  { "title": "Fargate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$fargate_logging_search | Total Log Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": " fields @timestamp, @message\n | filter @logStream like /(?i)var.log.containers.${fargate_logging_search}/\n | filter @message like /(?i)$searchable_pattern/\n | stats count(*) as logCount",
     "logGroupNames": [ "/aws/eks/uat/fargate-logging/" ],
     "logGroups": [
      {
       "accountId": "587878432697",
       "arn": "arn:aws:logs:us-east-1:587878432697:log-group:/aws/eks/uat/fargate-logging/:*",
       "name": "/aws/eks/uat/fargate-logging/"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "$fargate_logging_search | Total log count of $searchable_pattern",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": " fields @timestamp, @message\n | filter @logStream like /(?i)var.log.containers.${fargate_logging_search}/\n | filter @message like /(?i)$searchable_pattern/\n | stats count(*) as logCount",
     "logGroupNames": [ "/aws/eks/uat/fargate-logging/" ],
     "logGroups": [
      {
       "accountId": "587878432697",
       "arn": "arn:aws:logs:us-east-1:587878432697:log-group:/aws/eks/uat/fargate-logging/:*",
       "name": "/aws/eks/uat/fargate-logging/"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Fargate Logging",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expression": " fields @timestamp, @message\n | filter @logStream like /(?i)var.log.containers.${fargate_logging_search}/\n | filter @message like /(?i)$searchable_pattern/\n | sort @timestamp desc",
     "logGroupNames": [ "/aws/eks/uat/fargate-logging/" ],
     "logGroups": [
      {
       "accountId": "587878432697",
       "arn": "arn:aws:logs:us-east-1:587878432697:log-group:/aws/eks/uat/fargate-logging/:*",
       "name": "/aws/eks/uat/fargate-logging/"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Logs",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  }
 ]
}